{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shoot-auditlog-grafana.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "shoot-auditlog-grafana.name" . }}
    chart: {{ template "shoot-auditlog-grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}
