---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    helm.sh/chart: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret-auditlog-service-config: {{ include "auditlogconfig" . | sha256sum }}
        {{- if .Values.imageVectorOverwrite }}
        checksum/configmap-extension-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "name" . }}
      containers:
      - name: {{ include "name" . }}
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-shoot-auditlog-service
        - --config=/etc/auditlog-service/config.yaml
        - --max-concurrent-reconciles={{ .Values.controllers.concurrentSyncs }}
        - --webhook-config-namespace={{ .Release.Namespace }}
        - --webhook-config-server-port={{ .Values.webhookConfig.serverPort }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        ports:
        - name: webhook-server
          containerPort: {{ .Values.webhookConfig.serverPort }}
          protocol: TCP
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: auditlog-service-config
          mountPath: /etc/auditlog-service
          readOnly: true
        {{- if .Values.imageVectorOverwrite }}
        - name: extension-imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      volumes:
      - name: auditlog-service-config
        secret:
          secretName: {{ include "name" .}}-config
      {{- if .Values.imageVectorOverwrite }}
      - name: extension-imagevector-overwrite
        configMap:
          name: {{ include "name" .}}-imagevector-overwrite
          defaultMode: 420
      {{- end }}
