---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auditlog-proxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "auditlog-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
