---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-extension-shoot-auditlog-service
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-auditlog-service
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - gardener-extension-shoot-auditlog-service
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
