// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	unsafe "unsafe"

	proxy "github.com/gardener/gardener-extension-shoot-auditlog-service/pkg/apis/proxy"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*proxy.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_proxy_Configuration(a.(*Configuration), b.(*proxy.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_Configuration_To_v1alpha1_Configuration(a.(*proxy.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSConfiguration)(nil), (*proxy.TLSConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLSConfiguration_To_proxy_TLSConfiguration(a.(*TLSConfiguration), b.(*proxy.TLSConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.TLSConfiguration)(nil), (*TLSConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_TLSConfiguration_To_v1alpha1_TLSConfiguration(a.(*proxy.TLSConfiguration), b.(*TLSConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WebhookConfiguration)(nil), (*proxy.WebhookConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WebhookConfiguration_To_proxy_WebhookConfiguration(a.(*WebhookConfiguration), b.(*proxy.WebhookConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*proxy.WebhookConfiguration)(nil), (*WebhookConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_proxy_WebhookConfiguration_To_v1alpha1_WebhookConfiguration(a.(*proxy.WebhookConfiguration), b.(*WebhookConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Configuration_To_proxy_Configuration(in *Configuration, out *proxy.Configuration, s conversion.Scope) error {
	out.Provider = in.Provider
	out.ProviderConfig = *(*json.RawMessage)(unsafe.Pointer(&in.ProviderConfig))
	if err := Convert_v1alpha1_WebhookConfiguration_To_proxy_WebhookConfiguration(&in.WebhookConfiguration, &out.WebhookConfiguration, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Configuration_To_proxy_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_proxy_Configuration(in *Configuration, out *proxy.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_proxy_Configuration(in, out, s)
}

func autoConvert_proxy_Configuration_To_v1alpha1_Configuration(in *proxy.Configuration, out *Configuration, s conversion.Scope) error {
	out.Provider = in.Provider
	out.ProviderConfig = *(*json.RawMessage)(unsafe.Pointer(&in.ProviderConfig))
	if err := Convert_proxy_WebhookConfiguration_To_v1alpha1_WebhookConfiguration(&in.WebhookConfiguration, &out.WebhookConfiguration, s); err != nil {
		return err
	}
	return nil
}

// Convert_proxy_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_proxy_Configuration_To_v1alpha1_Configuration(in *proxy.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_proxy_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_TLSConfiguration_To_proxy_TLSConfiguration(in *TLSConfiguration, out *proxy.TLSConfiguration, s conversion.Scope) error {
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	return nil
}

// Convert_v1alpha1_TLSConfiguration_To_proxy_TLSConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_TLSConfiguration_To_proxy_TLSConfiguration(in *TLSConfiguration, out *proxy.TLSConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLSConfiguration_To_proxy_TLSConfiguration(in, out, s)
}

func autoConvert_proxy_TLSConfiguration_To_v1alpha1_TLSConfiguration(in *proxy.TLSConfiguration, out *TLSConfiguration, s conversion.Scope) error {
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	return nil
}

// Convert_proxy_TLSConfiguration_To_v1alpha1_TLSConfiguration is an autogenerated conversion function.
func Convert_proxy_TLSConfiguration_To_v1alpha1_TLSConfiguration(in *proxy.TLSConfiguration, out *TLSConfiguration, s conversion.Scope) error {
	return autoConvert_proxy_TLSConfiguration_To_v1alpha1_TLSConfiguration(in, out, s)
}

func autoConvert_v1alpha1_WebhookConfiguration_To_proxy_WebhookConfiguration(in *WebhookConfiguration, out *proxy.WebhookConfiguration, s conversion.Scope) error {
	out.HTTPPort = in.HTTPPort
	out.HTTPSPort = in.HTTPSPort
	if err := Convert_v1alpha1_TLSConfiguration_To_proxy_TLSConfiguration(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_WebhookConfiguration_To_proxy_WebhookConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_WebhookConfiguration_To_proxy_WebhookConfiguration(in *WebhookConfiguration, out *proxy.WebhookConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_WebhookConfiguration_To_proxy_WebhookConfiguration(in, out, s)
}

func autoConvert_proxy_WebhookConfiguration_To_v1alpha1_WebhookConfiguration(in *proxy.WebhookConfiguration, out *WebhookConfiguration, s conversion.Scope) error {
	out.HTTPPort = in.HTTPPort
	out.HTTPSPort = in.HTTPSPort
	if err := Convert_proxy_TLSConfiguration_To_v1alpha1_TLSConfiguration(&in.TLS, &out.TLS, s); err != nil {
		return err
	}
	return nil
}

// Convert_proxy_WebhookConfiguration_To_v1alpha1_WebhookConfiguration is an autogenerated conversion function.
func Convert_proxy_WebhookConfiguration_To_v1alpha1_WebhookConfiguration(in *proxy.WebhookConfiguration, out *WebhookConfiguration, s conversion.Scope) error {
	return autoConvert_proxy_WebhookConfiguration_To_v1alpha1_WebhookConfiguration(in, out, s)
}
